# Copyright (c) Microsoft. All rights reserved.
FROM mcr.microsoft.com/devcontainers/python:3.10

# Set the working directory to code
WORKDIR /code

# Copy the current directory contents into the container
COPY . .

RUN apt-get update && apt-get install git -y && apt-get install curl -y

# Install packages specified in requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN pip install git+https://github.com/camelot-dev/camelot.git

EXPOSE 5678

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run app when the container launches
CMD [ "gunicorn", "main:app" ]